title: test-course3
tagline: A brand new course on Learning Lab
description: test course for learning how this works
template:
  repo: test-course3-template
  name: test-course3
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
